
tasks:
  - name: Webserver
    command: >
      npm install -g browser-sync;
      browser-sync -f *.html -f *.js -f *.css --no-open --no-ui --listen 0.0.0.0 --port 8000

ports:
  - name: Webserver
    port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
